import { v4 as uuidv4 } from "uuid";
export const defaultData = [
  {
    id: uuidv4(),
    rollno: "101",
    name: "Aman Gupta",
    DOB: "2000-05-15",
    gender: "Male",
    contact: "9876543210",
    courses: "BCA",
    department: ["IT", "CS"],
    description: "Tech enthusiast",
    address: "Delhi",
  },
  {
    id: uuidv4(),
    rollno: "102",
    name: "Priya Sharma",
    DOB: "2001-08-22",
    gender: "Female",
    contact: "9123456780",
    courses: "B.Sc",
    department: ["Science"],
    description: "Loves research",
    address: "Mumbai",
  },
  {
    id: uuidv4(),
    rollno: "103",
    name: "Rohit Verma",
    DOB: "1999-12-10",
    gender: "Male",
    contact: "9988776655",
    courses: "B.Tech",
    department: ["ECE"],
    description: "Future engineer",
    address: "Bangalore",
  },
];
